image: python:3.5

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - mkdocs build


# removed until I figute out how to push code from gitlab
#deploy:
#  stage: deploy
#  script:
#    - pip install -r requirements.txt
#    - mkdocs gh-deploy
#  only:
#    - master
