image: python:3.5

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - mkdocs build

deploy:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - mkdocs gh-deploy
  only:
    - master
